version: '3'

services:
  server:
    container_name: 'server'
    image: nginx:latest
    expose:
      - 8082
    ports:
      - 8082:80
    volumes:
      - ./api:/var/www/api
      - ./server.conf:/etc/nginx/conf.d/default.conf
    links:
      - php

  php:
    container_name: 'php'
    image: php:7-fpm
    volumes:
      - ./api:/var/www/api