version: '3'

services:
  web:
    container_name: 'web'
    image: node:alpine
    working_dir: /app
    command: /bin/sh -c "yarn serve"
    expose:
      - 8080
    ports:
      - 8080:8080
    volumes:
      - ./:/app
    links:
      - server

  server:
    container_name: 'server'
    image: nginx:latest
    ports:
      - 8081:80
    volumes:
      - ./api:/var/www/api
      - ./server.conf:/etc/nginx/conf.d/default.conf
    links:
      - php

  php:
    container_name: 'php'
    image: php:7-fpm
    volumes:
      - ./api:/var/www/api